version: "2.1"

networks:
    default:

services:
    lavalink:
        image: fredboat/lavalink:master
        container_name: lavalink_dev
        volumes:
            - ./lavalink/application.yaml:/opt/Lavalink/application.yaml
        networks:
            - default

    bot:
        build:
            context: ./
            dockerfile: dev.Dockerfile
        container_name: bot_dev
        env_file:
            - bot.dev.env
        volumes:
            - ./:/app
        networks:
            - default
        depends_on:
            - lavalink
        links:
            - lavalink
